language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install sphinx~=1.5.3 sphinxcontrib-napoleon~=0.7
script:
  - pytest
  - make -C docs html
  - touch docs/html/.nojekyll
