language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install sphinx sphinxcontrib-napoleon
script:
  - pytest
  - make -C docs html
  - touch docs/build/html/.nojekyll
