language: python
cache: pip
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install sphinx sphinxcontrib-napoleon
script:
  - python setup.py test
  - make -C docs html
  - touch docs/build/html/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: master
  local_dir: docs/build/html
