name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-runner
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: python setup.py test
